http://localhost:8080/api/dictionary?userId=2
###
http://localhost:8080/api/dictionary/1
###
POST http://localhost:8080/api/private/dictionary
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6IkFkbWluIiwicGFzc3dvcmQiOiIxMjMzMjEifQ.AH4EQdVo4PVTNGZfA9d8QWiU1BX_iy-P9HmZ4CgP8mE
content-type: application/json

{
  "caption": "English",
  "description": "for myself",
  "userId": 6
}
###
PUT http://localhost:8080/api/private/dictionary
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Ik1hcmF0IiwicGFzc3dvcmQiOiIxMjMzMjEifQ.oeaBvNq0zzSEeyjh6S_bvm-2wQ3EMTSY3sub2aMpLEU
content-type: application/json

{
  "caption": "Hello",
  "description": "Привет",
  "dictionaryId": 2
}
###
DELETE http://localhost:8080/api/private/dictionary?id=5
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Ik1hcmF0IiwicGFzc3dvcmQiOiIxMjMzMjEifQ.oeaBvNq0zzSEeyjh6S_bvm-2wQ3EMTSY3sub2aMpLEU