http://localhost:8080/api/user
###
http://localhost:8080/api/user/1
###
POST http://localhost:8080/api/user
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Ik1hcmF0IiwicGFzc3dvcmQiOiIxMjMzMjEifQ.oeaBvNq0zzSEeyjh6S_bvm-2wQ3EMTSY3sub2aMpLEU

{
  "caption": "ADMIN",
  "description": "The Real",
  "login": "AdminHeHeHe",
  "password": "123321",
  "isSuperAdmin": true
}
###
PUT http://localhost:8080/api/private/user?id=1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Ik1hcmF0IiwicGFzc3dvcmQiOiIxMjMzMjEifQ.oeaBvNq0zzSEeyjh6S_bvm-2wQ3EMTSY3sub2aMpLEU

{
  "caption": "Updated",
  "description": "version",
  "login": "marat",
  "password": "123321Ok"
}
###
DELETE http://localhost:8080/api/private/user?id=5
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6IkFkbWluIiwicGFzc3dvcmQiOiIxMjMzMjEifQ.AH4EQdVo4PVTNGZfA9d8QWiU1BX_iy-P9HmZ4CgP8mE